package enumeration;

public enum CategorieVehicule {
	MICRO_URBAINES, MINI_CITADINES, CITADINES_POLYVALENTES, COMPACTES, BERLINES_TAILLE_S, BERLINES_TAILLE_M,
	BERLINES_TAILLE_L, SUV_TOUT_TERRAINS_PICK_UP
}
